import { createContext, useState } from "react";

export let MyStore = createContext();

export const MyContextProvider = ({ children }) => {
  const [unit, setUnit] = useState("C"); // °C or °F

  const [cities, setCities] = useState([
    {
      city: "Khulna, Bangladesh",
      time: "2:59 PM",
      temperature: { C: 32, F: 90 },
      condition: "Rainy",
      feelsLike: { C: 35, F: 95 },
      description: "Heavy rain with a chance of thunderstorms.",
      details: {
        airQuality: 156,
        wind: "1 mph",
        humidity: "54%",
        visibility: "3 mi",
        pressureIn: "27.65 in",
        pressureDeg: "66°",
      },
    },
    {
      city: "Dhaka, Bangladesh",
      time: "3:10 PM",
      temperature: { C: 34, F: 93 },
      condition: "Sunny",
      feelsLike: { C: 38, F: 100 },
      description: "Clear skies throughout the day.",
      details: {
        airQuality: 140,
        wind: "5 mph",
        humidity: "45%",
        visibility: "6 mi",
        pressureIn: "28.1 in",
        pressureDeg: "70°",
      },
    },
    {
      city: "Chattogram, Bangladesh",
      time: "2:40 PM",
      temperature: { C: 31, F: 88 },
      condition: "Cloudy",
      feelsLike: { C: 33, F: 91 },
      description: "Overcast with a light sea breeze.",
      details: {
        airQuality: 120,
        wind: "3 mph",
        humidity: "60%",
        visibility: "4 mi",
        pressureIn: "27.8 in",
        pressureDeg: "65°",
      },
    },
    {
      city: "Sylhet, Bangladesh",
      time: "3:20 PM",
      temperature: { C: 29, F: 84 },
      condition: "Rainy",
      feelsLike: { C: 30, F: 86 },
      description: "Scattered thunderstorms expected.",
      details: {
        airQuality: 130,
        wind: "7 mph",
        humidity: "70%",
        visibility: "5 mi",
        pressureIn: "27.5 in",
        pressureDeg: "68°",
      },
    },
    // Added 20 More
    {
      city: "Bhopal, India",
      time: "9:59 AM",
      temperature: { C: 35, F: 95 },
      condition: "Sunny",
      feelsLike: { C: 37, F: 99 },
      description: "Hot and sunny, clear skies.",
      details: {
        airQuality: 180,
        wind: "4 mph",
        humidity: "40%",
        visibility: "5 mi",
        pressureIn: "29.2 in",
        pressureDeg: "72°",
      },
    },
    {
      city: "New York, USA",
      time: "12:29 AM",
      temperature: { C: 22, F: 72 },
      condition: "Clear",
      feelsLike: { C: 22, F: 72 },
      description: "Clear night with a gentle breeze.",
      details: {
        airQuality: 45,
        wind: "8 mph",
        humidity: "55%",
        visibility: "10 mi",
        pressureIn: "30.1 in",
        pressureDeg: "75°",
      },
    },
    {
      city: "London, UK",
      time: "5:29 AM",
      temperature: { C: 15, F: 59 },
      condition: "Overcast",
      feelsLike: { C: 14, F: 57 },
      description: "Cloudy skies with a chance of drizzle.",
      details: {
        airQuality: 55,
        wind: "12 mph",
        humidity: "75%",
        visibility: "6 mi",
        pressureIn: "29.8 in",
        pressureDeg: "69°",
      },
    },
    {
      city: "Tokyo, Japan",
      time: "1:29 PM",
      temperature: { C: 28, F: 82 },
      condition: "Partly Cloudy",
      feelsLike: { C: 30, F: 86 },
      description: "Humid with sun and clouds.",
      details: {
        airQuality: 80,
        wind: "10 mph",
        humidity: "68%",
        visibility: "8 mi",
        pressureIn: "29.9 in",
        pressureDeg: "71°",
      },
    },
    {
      city: "Sydney, Australia",
      time: "2:29 PM",
      temperature: { C: 18, F: 64 },
      condition: "Sunny",
      feelsLike: { C: 17, F: 63 },
      description: "Pleasant winter day with clear skies.",
      details: {
        airQuality: 30,
        wind: "15 mph",
        humidity: "50%",
        visibility: "12 mi",
        pressureIn: "30.2 in",
        pressureDeg: "76°",
      },
    },
    {
      city: "Cairo, Egypt",
      time: "6:29 AM",
      temperature: { C: 38, F: 100 },
      condition: "Clear",
      feelsLike: { C: 39, F: 102 },
      description: "Very hot and dry conditions.",
      details: {
        airQuality: 160,
        wind: "6 mph",
        humidity: "20%",
        visibility: "7 mi",
        pressureIn: "29.7 in",
        pressureDeg: "68°",
      },
    },
    {
      city: "Moscow, Russia",
      time: "7:29 AM",
      temperature: { C: -5, F: 23 },
      condition: "Snow",
      feelsLike: { C: -10, F: 14 },
      description: "Light snowfall throughout the morning.",
      details: {
        airQuality: 65,
        wind: "9 mph",
        humidity: "85%",
        visibility: "2 mi",
        pressureIn: "29.5 in",
        pressureDeg: "65°",
      },
    },
    {
      city: "Rio de Janeiro, Brazil",
      time: "1:29 AM",
      temperature: { C: 25, F: 77 },
      condition: "Humid",
      feelsLike: { C: 27, F: 81 },
      description: "Warm and humid night.",
      details: {
        airQuality: 90,
        wind: "3 mph",
        humidity: "88%",
        visibility: "5 mi",
        pressureIn: "29.9 in",
        pressureDeg: "70°",
      },
    },
    {
      city: "Paris, France",
      time: "6:29 AM",
      temperature: { C: 19, F: 66 },
      condition: "Partly Cloudy",
      feelsLike: { C: 19, F: 66 },
      description: "A mild and pleasant morning.",
      details: {
        airQuality: 70,
        wind: "7 mph",
        humidity: "65%",
        visibility: "9 mi",
        pressureIn: "30.0 in",
        pressureDeg: "73°",
      },
    },
    {
      city: "Beijing, China",
      time: "12:29 PM",
      temperature: { C: 26, F: 79 },
      condition: "Hazy",
      feelsLike: { C: 27, F: 81 },
      description: "Hazy sun due to high pollution.",
      details: {
        airQuality: 250,
        wind: "2 mph",
        humidity: "60%",
        visibility: "3 mi",
        pressureIn: "29.8 in",
        pressureDeg: "69°",
      },
    },
    {
      city: "Dubai, UAE",
      time: "8:29 AM",
      temperature: { C: 42, F: 108 },
      condition: "Sunny",
      feelsLike: { C: 45, F: 113 },
      description: "Extremely hot and sunny.",
      details: {
        airQuality: 190,
        wind: "11 mph",
        humidity: "25%",
        visibility: "10 mi",
        pressureIn: "29.6 in",
        pressureDeg: "67°",
      },
    },
    {
      city: "Toronto, Canada",
      time: "12:29 AM",
      temperature: { C: 17, F: 63 },
      condition: "Windy",
      feelsLike: { C: 15, F: 59 },
      description: "Clear but windy conditions.",
      details: {
        airQuality: 35,
        wind: "20 mph",
        humidity: "58%",
        visibility: "12 mi",
        pressureIn: "30.1 in",
        pressureDeg: "75°",
      },
    },
    {
      city: "Singapore",
      time: "12:29 PM",
      temperature: { C: 31, F: 88 },
      condition: "Thunderstorm",
      feelsLike: { C: 34, F: 93 },
      description: "Hot and humid with afternoon thunderstorms.",
      details: {
        airQuality: 75,
        wind: "5 mph",
        humidity: "82%",
        visibility: "4 mi",
        pressureIn: "29.7 in",
        pressureDeg: "68°",
      },
    },
    {
      city: "Mumbai, India",
      time: "9:59 AM",
      temperature: { C: 33, F: 91 },
      condition: "Partly Cloudy",
      feelsLike: { C: 36, F: 97 },
      description: "Hot and humid with some cloud cover.",
      details: {
        airQuality: 210,
        wind: "8 mph",
        humidity: "75%",
        visibility: "4 mi",
        pressureIn: "29.4 in",
        pressureDeg: "64°",
      },
    },
    {
      city: "Berlin, Germany",
      time: "6:29 AM",
      temperature: { C: 16, F: 61 },
      condition: "Cloudy",
      feelsLike: { C: 15, F: 59 },
      description: "Cool and overcast morning.",
      details: {
        airQuality: 50,
        wind: "10 mph",
        humidity: "72%",
        visibility: "7 mi",
        pressureIn: "29.9 in",
        pressureDeg: "71°",
      },
    },
    {
      city: "Cape Town, South Africa",
      time: "6:29 AM",
      temperature: { C: 14, F: 57 },
      condition: "Showers",
      feelsLike: { C: 13, F: 55 },
      description: "Light rain showers expected.",
      details: {
        airQuality: 25,
        wind: "18 mph",
        humidity: "80%",
        visibility: "5 mi",
        pressureIn: "30.0 in",
        pressureDeg: "74°",
      },
    },
    {
      city: "Los Angeles, USA",
      time: "9:29 PM",
      temperature: { C: 24, F: 75 },
      condition: "Clear",
      feelsLike: { C: 24, F: 75 },
      description: "A warm and clear evening.",
      details: {
        airQuality: 95,
        wind: "4 mph",
        humidity: "60%",
        visibility: "10 mi",
        pressureIn: "30.0 in",
        pressureDeg: "73°",
      },
    },
    {
      city: "Mexico City, Mexico",
      time: "11:29 PM",
      temperature: { C: 15, F: 59 },
      condition: "Partly Cloudy",
      feelsLike: { C: 14, F: 57 },
      description: "Cool night with some clouds.",
      details: {
        airQuality: 175,
        wind: "2 mph",
        humidity: "50%",
        visibility: "8 mi",
        pressureIn: "30.1 in",
        pressureDeg: "75°",
      },
    },
    {
      city: "Rome, Italy",
      time: "6:29 AM",
      temperature: { C: 25, F: 77 },
      condition: "Sunny",
      feelsLike: { C: 25, F: 77 },
      description: "Beautiful sunny morning in Rome.",
      details: {
        airQuality: 85,
        wind: "3 mph",
        humidity: "55%",
        visibility: "10 mi",
        pressureIn: "30.2 in",
        pressureDeg: "76°",
      },
    },
    {
      city: "Buenos Aires, Argentina",
      time: "1:29 AM",
      temperature: { C: 12, F: 54 },
      condition: "Clear",
      feelsLike: { C: 11, F: 52 },
      description: "A cool and clear winter night.",
      details: {
        airQuality: 40,
        wind: "6 mph",
        humidity: "70%",
        visibility: "9 mi",
        pressureIn: "30.1 in",
        pressureDeg: "75°",
      },
    },
  ]);
  const [currentWeather, setCurrentWeather] = useState(cities[0]);

  return (
    <MyStore.Provider
      value={{ unit, setUnit, currentWeather, setCurrentWeather, cities }}
    >
      {children}
    </MyStore.Provider>
  );
};
